neovim: fix cursorline autocmd
georgijd/dotfiles pull request #2
Opened 2022-10-03 23:58 UTC by adrian5

Hey Georgi, I just wanted to say thanks for sharing your nvim dotfiles, they were a treasure trove of interesting tweaks!

Since there's no `Issue` or `Discussions` panel in this repo, I thought I'd file a PR. I'm pretty sure that `VimLeave` was meant to be `WinLeave`. You don't have to merge this, just pointing it out.

2022-10-12 15:17 UTC, georgijd-form3 commented
Hi @adrian5 ,

Thank you for the kind words! Actually I think we might need both events, the intention behind `VimLeave` was to execute the autocmd when I move out of nvim into another tmux split. But you're right that we should also use `WinLeave` (and perhaps `BufWinLeave`). It will become consistent with the `{ 'VimEnter', 'WinEnter', 'BufWinEnter' }` autocmd

2022-10-12 15:19 UTC, georgijd commented
Hi @adrian5 ,

Thank you for the kind words! Actually I think we might need both events, the intention behind `VimLeave` was to execute the autocmd when I move out of nvim into another tmux split. But you're right that we should also use `WinLeave` (and perhaps `BufWinLeave`). It will become consistent with the `{ 'VimEnter', 'WinEnter', 'BufWinEnter' }` autocmd

2022-10-12 15:20 UTC, georgijd requested changes

2022-10-12 15:20 UTC, georgijd commented on nvim/lua/user/autocmd.lua
> +vim.api.nvim_create_autocmd('WinLeave', {
```suggestion
vim.api.nvim_create_autocmd({ 'VimLeave', 'WinLeave', 'BufWinLeave' }, {
```

2022-10-12 18:21 UTC, adrian5 commented
Ah OK, I don't use tmux so I didn't even consider that. I really assumed this was a mixup due to the similar names.

I've applied the requested changes. But if you prefer to make the changes yourself and close this PR, I won't hold it against you! :wink:

2022-10-13 10:33 UTC, georgijd-form3 approved these changes

2022-10-13 10:35 UTC, georgijd approved these changes

2022-10-13 10:40 UTC, merged